name: Create Lineage Builder

runs:
  using: composite
  steps:
    - name: Prepare Action
      run: |
        CheckoutDir=$GITHUB_WORKSPACE
        echo "CheckoutDir=$CheckoutDir" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python-is-python3 wget ca-certificates openssh-client
        # Ubuntu Mantic Only
        # wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb && dpkg -i libtinfo5_6.4-2_amd64.deb && rm -f libtinfo5_6.4-2_amd64.deb
        # wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.4-2_amd64.deb && dpkg -i libncurses5_6.4-2_amd64.deb && rm -f libncurses5_6.4-2_amd64.deb
        # Before mantic use
        sudo apt-get install -y --no-install-recommends lib32ncurses5-dev libncurses5 libncurses5-dev
        git lfs install
        whoami
        mkdir -p $CheckoutDir/bin && mkdir -p $CheckoutDir/android/lineage
        curl https://storage.googleapis.com/git-repo-downloads/repo > $CheckoutDir/bin/repo
        chmod a+x $CheckoutDir/bin/repo
        echo "$CheckoutDir/bin" >> $GITHUB_PATH
        git config --global user.email "fake@localhost.local"
        git config --global user.name "fake"
      shell: bash

    - name: Cleanup
      run: sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*
      shell: bash

    - name: Execute Action
      run: |
        cd $CheckoutDir/android/lineage
        repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --depth 1 --git-lfs
        #patch $CheckoutDir/android/lineage/.repo/repo/git_command.py < $CheckoutDir/patches/git_command.patch
        #repo sync -c --force-sync --no-clone-bundle --no-tags -j$(nproc --all)
        #repo sync --force-sync --no-clone-bundle --no-tags -c -n -j$(nproc --all) && repo sync --force-sync --no-clone-bundle --no-tags -c -l -j16
      shell: bash

    - name: Show Info
      run: |
        echo $OUT
        sudo du -h --max-depth=1 $CheckoutDir/android/lineage/
      shell: bash
